### ISSUE TITLE
error: Could not access '/tmp/chezmoi-diff1963783521/.config/<folder>/null

### ISSUE THREAD

**Issue by dgudim** [VorpalBlade/chezmoi_modify_manager#77] opened 2024-02-08 14:20 UTC
## Describe the bug
Doing a `chezmoi diff` on a machine where the target files parent folder does not exist produces and error
```
error: Could not access '/tmp/chezmoi-diff1963783521/.config/simplescreenrecorder/null'
chezmoi: exit status 1
read /tmp/chezmoi-diff1963783521/.config/simplescreenrecorder: is a directory
```

## To Reproduce
1. Add a file using chezmoi modify manager
2. Make sure that on another machine the folder where the config should be located does not exist
3. Do chemoi diff on that other machine
4. Observe

## Expected behavior
No errors

## Actual behavior
Chezmoi exits with exit code 1

## Output of `chezmoi_modify_manager --doctor`

<details>

```console
$ chezmoi_modify_manager --doctor
RESULT    CHECK                MESSAGE
Info      version              3.0.0
Info      rustc-version        1.75.0
Info      host                 os=linux, arch=x86_64, info=EndeavourOS Rolling Release (rolling) [64-bit]
Ok        has-chezmoi          Chezmoi found. Version: chezmoi version v2.46.0, built at 2024-01-26T07:31:10Z
Ok        in-path              chezmoi_modify_manager is in PATH at /usr/bin/chezmoi_modify_manager
Ok        has-ignore           Ignore of **/*.src.ini found
Ok        no-hook-script       No legacy hook script found

Output of chezmoi doctor:
RESULT    CHECK                       MESSAGE
warning   version                     v2.46.0, built at 2024-01-26T07:31:10Z
ok        latest-version              v2.46.0
ok        os-arch                     linux/amd64 (EndeavourOS)
ok        uname                       Linux portable-heater 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux
ok        go-version                  go1.21.6 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-02-08T14:59:24+02:00
ok        source-dir                  ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries          no suspicious entries
ok        working-tree                ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/bash
ok        cd-args                     /bin/bash
ok        diff-command                found /usr/bin/delta
ok        edit-command                found /usr/bin/nano
ok        edit-args                   /usr/bin/nano
ok        git-command                 found /usr/bin/git, version 2.43.0
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/bash
ok        shell-args                  /bin/bash
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.4.4
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
ok        keepassxc-command           found /usr/bin/keepassxc-cli, version 2.7.6
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```
</details>

**Comment by VorpalBlade** [comment] 2024-02-08 16:10
Reading the output I think this is a bug in chezmoi itself? It will be a few days before I have time to look into this. But it sounds like there is a simple workaround for now: create the folder by hand.

**Comment by VorpalBlade** [comment] 2024-02-09 18:26
Huh, I'm not able to recreate it. If I understand you correctly the following sequence of events should cause the issue even on a single computer:

```bash
cd $(chezmoi source-path)
mkdir -p testdir/testdir2
echo "foo" > dummy.src.ini
cat << EOF > modify_dummy.tmpl
#!/usr/bin/env chezmoi_modify_manager

# This is needed to figure out where the source file is on older Chezmoi versions.
# See https://github.com/twpayne/chezmoi/issues/2934
source "{{ .chezmoi.sourceDir }}/{{ .chezmoi.sourceFile | trimSuffix ".tmpl" | replace "modify_" "" }}.src.ini"

# Add your ignores and transforms here
#ignore section "my-section"
#ignore "exact section name without brackets" "exact key name"
#ignore regex "section.*" "key_prefix_.*"
#transform "section" "key" transform_name read="the docs" for="more detail on transforms"
EOF
chezmoi diff
```

For me that works normally (assuming bash. zsh doesn't support here docs I learned today!):

```console
$ chezmoi diff
diff --git a/testdir b/testdir
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/testdir
diff --git a/testdir/testdir2 b/testdir/testdir2
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/testdir/testdir2
diff --git a/testdir/testdir2/dummy b/testdir/testdir2/dummy
new file mode 100644
index 0000000000000000000000000000000000000000..257cc5642cb1a054f08cc83f2d943e56fd3ebe99
--- /dev/null
+++ b/testdir/testdir2/dummy
@@ -0,0 +1 @@
+foo
```

So there must be something more to it. Could you share:
1. The specific names of the modify script and src.ini
2. The contents of the modify script. I'm very suspicious of the "null" part there.

**Comment by VorpalBlade** [comment] 2024-02-09 19:15
Hm, sounds like delta (never heard about it before) doesn't deal with `/dev/null` as an input gracefully. Normal diff does. In fact `git diff` will generate a patch against `/dev/null` for newly added files, so I *believe* this is kind of the standard way of doing things.

**Comment by VorpalBlade** [comment] 2024-02-09 19:16
Link to chezmoi bug if anyone finds this in the future: https://github.com/twpayne/chezmoi/issues/3548

Closing as "not a bug in this software" (possibly a bug in other software)

**Closed by VorpalBlade** 2024-02-09 19:16 UTC
Labels: bug

**Comment by dgudim** [comment] 2024-02-09 19:18
I think it's not about /dev/null, it's about the second parameter being set to a directory. Because delta deals with new files just fine
